services:
  dokalab_blog_db:
    image: postgres:17-alpine
    container_name: dokalab_blog_db_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: dokalab_blog_db
    ports:
      - "5436:5432"
    volumes:
      - dokalab_blog_db:/var/lib/postgresql/data
    networks:
      - dokalab_personal_web_network
    restart: unless-stopped

  dokalab_s3_db:
    image: postgres:17-alpine
    container_name: dokalab_s3_db_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: dokalab_s3_db
    ports:
      - "5440:5432"
    volumes:
      - dokalab_s3_db:/var/lib/postgresql/data
    networks:
      - dokalab_personal_web_network
    restart: unless-stopped

  dokalab_s3_minio_storage:
    image: quay.io/minio/minio
    container_name: dokalab_s3_minio_storage
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_NOTIFY_KAFKA_ENABLE_MINIO: "on"
      MINIO_NOTIFY_KAFKA_BROKERS_MINIO: "kafka:9092"
      MINIO_NOTIFY_KAFKA_TOPIC_MINIO: "minio-events"
      MINIO_NOTIFY_KAFKA_VERSION_MINIO: "0.10.2"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - dokalab_s3_minio_storage:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - dokalab_personal_web_network
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - dokalab_personal_web_network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    networks:
      - dokalab_personal_web_network
    restart: unless-stopped

volumes:
  dokalab_blog_db:
    driver: local
  dokalab_s3_db:
    driver: local
  dokalab_s3_minio_storage:
    driver: local

networks:
  dokalab_personal_web_network:
    external: true